name: axxos
favicon: null
layout_spectrum: 0.5644856498111039
typography_spectrum: 0.01282653259113431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7393a0'
    - '#9a252e'
    - '#146894'
    - '#f38874'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
